{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(vault_client_count_monthly_namespace_clients,namespace)"
    }
   },
   { "name": "client_cost", "label": "Cost per Client", "query": "23.45" }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Billing Period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_client_count_activity_period_info",
     "legendFormat": "{{start_time}}"
    },
    {
     "expr": "vault_client_count_activity_period_info",
     "legendFormat": "{{end_time}}"
    }
   ]
  },
  {
   "title": "approx. Total Client Costs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (client_type) (vault_client_count_current_namespace_clients)) * $client_cost",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Disitribution per Namespace",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (vault_client_count_current_mount_clients)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Clients",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vault_client_count_current_namespace_clients)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Clients per Month",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "sort_desc(sum by (month) (vault_client_count_monthly_namespace_clients))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Namespaces",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "topk(5, sum by (namespace) (vault_client_count_current_namespace_clients))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\"$namespace\" Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "namespace"
  },
  {
   "title": "Client Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (client_type) (vault_client_count_current_namespace_clients{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of Total Client Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(vault_client_count_current_namespace_clients{namespace=\"$namespace\"})\n/\nscalar(sum(vault_client_count_current_namespace_clients))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Clients prepared to Total Client Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vault_client_count_current_namespace_clients{namespace=\"$namespace\"})",
     "legendFormat": "$namespace"
    },
    {
     "expr": "sum(vault_client_count_current_namespace_clients{namespace!=\"$namespace\"})",
     "legendFormat": "Cluster"
    }
   ]
  },
  {
   "title": "Client Count grouped by client_type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "targets": [
    {
     "expr": "sort_desc(sum by (month, client_type) (vault_client_count_monthly_namespace_clients{namespace=\"root\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "approx. Client Costs per Namepace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (client_type) (vault_client_count_current_namespace_clients{namespace=\"$namespace\"})) * $client_cost",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Count grouped by mount_type",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sort_desc(sum by (month, mount_type) (vault_client_count_monthly_mount_clients{ namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Count grouped by mount_path",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "sort_desc(sum by (month, mount_path) (vault_client_count_monthly_mount_clients{namespace=\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}